<a href="https://colab.research.google.com/github/Luizfilipe99/C11/blob/main/Exercicio_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Exercicio 1

In [4]:
import numpy as np

arr_1 = np.ones([8])

arr_2 = np.random.randint(0, 10, 8)

arr_3 = arr_1 + arr_2

if arr_3.sum() >= 40:
  matriz = arr_3.reshape(4, 2)
else:
  matriz = arr_3.reshape(2, 4)


#Exercicio 2

In [10]:
import numpy as np

arr = np.zeros([4])
mtz = arr.reshape(2, 2)

linha = np.random.randint(0, 2)
coluna = np.random.randint(0, 2)

mtz[linha, coluna] = 1

l=-1
c=-1

for i in range(3):
  l = int(input("Escolha a linha (0 ou 1): "))
  c = int(input("Escolha a coluna (0 ou 1): "))

  if mtz[l, c] == 1:
    print('Game Over! :( Try Again!')
    break
  else:
    if i == 2:
      print( 'Congratulations! You beat the game! :)')




Escolha a linha (0 ou 1): 0
Escolha a coluna (0 ou 1): 0
Game Over! :( Try Again!


#Exercicio 3

In [19]:
import numpy as np

linha = np.random.randint(1, 30)
coluna = np.random.randint(1, 30)

mtz = np.random.randint(0, 10,[linha , coluna])

if mtz.size % 2 == 0:
    print('Matriz PAR.')
else:
    print('Matriz ÍMPAR.')

Matriz PAR.


#Exercicio 4

In [20]:
import numpy as np

np.random.seed(10)

mtz = np.random.randint(1, 51, [4, 4])

print(mtz.mean(axis=0))
print(mtz.mean(axis=1))

print(mtz.mean(axis=0).max())
print(mtz.mean(axis=1).max())


valores, contagens = np.unique(mtz, return_counts=True)

print("Quantidade de aparições de cada número:")
for num, qtd in zip(valores, contagens):
    print(f"O número {num} aparece {qtd} vez(es)")

numeros_duas_vezes = valores[contagens == 2]

print("\nNúmeros que aparecem 2 vezes:")
print(numeros_duas_vezes)


[29.75 24.25 33.75 20.25]
[16.   33.75 34.5  23.75]
33.75
34.5
Quantidade de aparições de cada número:
O número 1 aparece 2 vez(es)
O número 9 aparece 1 vez(es)
O número 10 aparece 2 vez(es)
O número 16 aparece 1 vez(es)
O número 26 aparece 1 vez(es)
O número 29 aparece 1 vez(es)
O número 30 aparece 2 vez(es)
O número 37 aparece 1 vez(es)
O número 41 aparece 1 vez(es)
O número 43 aparece 1 vez(es)
O número 49 aparece 1 vez(es)
O número 50 aparece 2 vez(es)

Números que aparecem 2 vezes:
[ 1 10 30 50]


#Exercicio 5

In [ ]:
import numpy as np

matriz_zeros = np.zeros((3, 3), dtype=int)
matriz_ones = np.ones((3, 3), dtype=int)

mtz = (matriz_ones + matriz_zeros) * 9

mtz = mtz.reshape(9)

#Exercicio 6

In [21]:
import numpy as np

arr = np.arange(10, 31, 2)

print(arr.max())
print(arr.argmax())
print(arr.sum())

30
10
220


#Exercicio 7

In [23]:
import numpy as np

np.random.seed(7)

arr_1 = np.random.randint(1, 11, 5)

arr_2 = np.random.randint(1, 11, 5)

arr_3 = np.concatenate((arr_1, arr_2))

mtz = arr_3.reshape(2, 5)